//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class trafficEntities : DbContext
    {
        public trafficEntities()
            : base("name=trafficEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Busz> Buszs { get; set; }
        public virtual DbSet<BuszAllapot> BuszAllapots { get; set; }
        public virtual DbSet<Garaz> Garazs { get; set; }
        public virtual DbSet<Jelze> Jelzes { get; set; }
        public virtual DbSet<Megallok> Megalloks { get; set; }
        public virtual DbSet<Sofor> Sofors { get; set; }
        public virtual DbSet<Uzenet> Uzenets { get; set; }
        public virtual DbSet<Vonal> Vonals { get; set; }
        public virtual DbSet<VonalBusz> VonalBuszs { get; set; }
        public virtual DbSet<VonalBuszSofor> VonalBuszSofors { get; set; }
        public virtual DbSet<VonalMegallok> VonalMegalloks { get; set; }
        public virtual DbSet<Felszalla> Felszallas { get; set; }
    }
}
