//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class VonalMegallok
    {
        public int vonalMegalloiId { get; set; }
        public Nullable<int> megalloId { get; set; }
        public Nullable<int> vonalId { get; set; }
    
        public virtual Megallok Megallok { get; set; }
        public virtual Vonal Vonal { get; set; }
    }
}
